server:
  port: 8888

spring:
  application:
    name: demo
  datasource:
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  #    schema: classpath:static/init.sql
  #    data: classpath:static/data.sql
  #    initialization-mode: always
  jpa:
    show-sql: true

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.example.demo.entity


logging:
  level:
    com:
      example:
        demo:
          repository: debug
